version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
    hostname: host.docker.internal
    ports:
      - "1337:1337"
    environment:
      - SERVER_PORT=1337
  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    # alternatively,
    # build: .
    ports:
      - "3000:3000"
    command: >
      --upstream-host=arbeidsplassen:4000
      --log-level=info
      --bind-address=0.0.0.0:3000
      --ingress=http://localhost:3000
      --openid.well-known-url=http://host.docker.internal:1337/default/.well-known/openid-configuration
      --openid.client-id=bogus
      --openid.post-logout-redirect-uri http://localhost:3000
      --redis.address=redis:6379
      --redis.tls=false
      --log-format=text
    restart: on-failure
    environment:
      WONDERWALL_OPENID_CLIENT_JWK: >
        {
          "kty":"RSA",
          "alg":"RS256",
          "use":"sig",
          "p":"_xCPvqs85ZZVg460Qfot26rQoNRPTOVDo5p4nqH3ep6BK_5TvoU5LFXd26W-1V1Lc5fcvvftClPOT201xgat4DVtliNtoc8od_tWr190A3AzbsAVFOx0nKa5uhLBxP9SsPM84llp6PXF6QTMGFiPYuoLDaQQqL1K4BbHq3ZzF2M",
          "q":"7QLqW75zkfSDrn5rMoF50WXyB_ysNx6-2SvaXKGXaOn80IR7QW5vwkleJnsdz_1kr04rJws2p4HBJjUFfSJDi1Dapj7tbIwb0a1szDs6Y2fAa3DlzgXZCkoE2TIrW6UITgs14pI_a7RasclE71FpoZ78XNBvj3NmZugkNLBvRjs",
          "d":"f7aT4poed8uKdcSD95mvbfBdb6X-M86d99su0c390d6gWwYudeilDugH9PMwqUeUhY0tdaRVXr6rDDIKLSE-uEyaYKaramev0cG-J_QWYJU2Lx-4vDGNHAE7gC99o1Ee_LXqMDCBawMYyVcSWx7PxGQfzhSsARsAIbkarO1sg9zsqPS4exSMbK8wyCTPgRbnkB32_UdZSGbdSib1jSYyyoAItZ8oZHiltVsZIlA97kS4AGPtozde043NC7Ik0uEzgB5qJ_tR7vW8MfDrBj6da2NrLh0UH-q28dooBO1vEu0rvKZIescXYk9lk1ZakHhhpZaLykDOGzxCpronzP3_kQ",
          "e":"AQAB",
          "qi":"9kMIR6pEoiwN3M6O0n8bnh6c3KbLMoQQ1j8_Zyir7ZIlmRpWYl6HtK0VnD88zUuNKTrQa7-jfE5uAUa0PubzfRqybACb4S3HIAuSQP00_yCPzCSRrbpGRDFqq-8eWVwI9VdiN4oqkaaWcL1pd54IDcHIbfk-ZtNtZgsOlodeRMo",
          "dp":"VUecSAvI2JpjDRFxg326R2_dQWi6-uLMsq67FY7hx8WnOqZWKaUxcHllLENGguAmkgd8bv1F6-YJXNUO3Z7uE8DJWyGNTkSNK1CFsy0fBOdGywi-A7jrZFT6VBRhZRRY-YDaInPyzUkfWsGX26wAhPnrqCvqxgBEQJhdOh7obDE",
          "dq":"7EUfw92T8EhEjUrRKkQQYEK0iGnGdBxePLiOshEUky3PLT8kcBHbr17cUJgjHBiKqofOVNnE3i9nkOMCWcAyfUtY7KmGndL-WIP-FYplpnrjQzgEnuENgEhRlQOCXZWjNcnPKdKJDqF4WAtAgSIznz6SbSQMUoDD8IoyraPFCck",
          "n":"7CU8tTANiN6W_fD9SP1dK2vQvCkf7-nwvBYe5CfANV0_Bb0ZmQb77FVVsl1beJ7EYLz3cJmL8Is1RCHKUK_4ydqihNjEWTyZiQoj1i67pkqk_zRvfQa9raZR4uZbuBxx7dWUoPC6fFH2F_psAlHW0zf90fsLvhB6Aqq3uvO7XXqo8qNl9d_JSG0Rg_2QUYVb0WKmPVbbhgwtkFu0Tyuev-VZ9IzTbbr5wmZwEUVY7YAi73pDJkcZt5r2WjOF_cuIXe-O2vwbOrRgmJfHO9--mVLdATnEyrb6q2oy_75h6JjP-R4-TD1hyoFFoE2gmj-kSS6Z_Gggljs3Aw7--Nh10Q"
        }
  arbeidsplassen:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
    - "4000:4000"
    environment:
      - TOKEN_X_WELL_KNOWN_URL=http://host:docker:internal:1337/tokenx/:well-known/openid-configuration
      - IDPORTEN_WELL_KNOWN_URL=http://host.docker.internal:1337/idporten/.well-known/openid-configuration
      - TOKEN_X_CLIENT_ID=local-token-x-client-id
      - IDPORTEN_CLIENT_ID=local-idporten-client-id
      - TOKEN_X_PRIVATE_JWK='{"p":"1KMmKh85qonPCvMfbIyDbaSWeeBuMgJ3ISlLwV768PMR3vyFmaahYkAwRlG2QvDG4c4UDzqroaWlZ_5REC4M0oMFlWvZ6N4raWKteqyUxFChjDMpsFj1o_i4XYkPp_rB3ehMVvpVE64EylTe9_E0cLwFir82xA6pP8ho_BC6jtk","kty":"RSA","q":"nvKKaS1AG02qKnlFSYtKxyEXu-6sJr8GdSO0IYgvxBIboIxXwW14OqFY8aBQTDCrtXCSkwhQyCYwrhBZCpWgFhTedxefKfdzKzB9E4peaymnKOfjX4BaliG_j8z9_yavPOFDgsDdccbb5tqPq6OkCmZpTveIfygaJFc9N1-Fbr8","d":"JRdFU4dUucb8T6_9BR34B9x8zeyZA4vKN0hU2Ne5sf9_uahAsUAxSuQloAUC_I8yVURYC-ldl0RGNtH6FqWYZGaKo-92haOv6KRdHH4--8e44IIz3_3ySrTSskJyW018mP5uj6riCl-NJKCoAR4PfcwHXxj0fTZpdkm0g_ZuQeHyhbccgGO5y4xpFblzxmNv9FOwFtfsmRhdbp4XTtghFmT5y-eK5WhLA2evv_9zZRwgpp-BKjEqW2vBvEznnHDLGrK2pCtMrLv7VFKeaQlk01jRh-Old0Cola8xRHnPNFRVuGcaJbxbc83kJgPosK7gwMRU1ShOArPEIRcsWMzpwQ","e":"AQAB","use":"sig","kid":"jXDxKRE6a4jogcc4HgkDq3uVgQ0","qi":"k_FPIPmDVCwjxhdNb0zLg16bght6nkGfxPgS57dRslN_eEWy_FJNdDMmRQ17I0XLal-0ciRO4Q3pJg52vPX84y-tmA6OkTo5cbPX9NOhUz5I0bdahGLsBADI8Hod9g-WPw9peIaF9K1U335j_-M4Bw-35XL9kfFExrv28Ael594","dp":"h4LqAZIgyARHRG0oq57o62km1MkosQpNLX8J3lRPjFr8GqXH5uIAm4LYwRe2FfcoaCNTOVlkpAHS5fF3a95NIaOKXW18VCGyfNj8Qd_Wdz4DljvM56vp7_PEWyfMKHtwLaGrdQrYSVBvkRqBdnXru6S3y3KMzmmhhxqLfYiTvBE","alg":"RS256","dq":"fkdNRaBItShv0AzGylYa07dr5sgJB0NuuvPhsV5ELK8COfwl4Cu7gEEdq-HkyZNFaAIGwT-zBkCpHjEovKsBI2nzEIS41Bue6So9xJ-Cwfq2rl4Em6Qa0_n9-h4vkV3HjUOeYiweAr2tiWwNBp0cv5J7idxJGlTe6A5TOUHvfXs","n":"hAYmv2IqZQzSGTK7RixXgl7yEu3MgG2kuK4inAK0cSOseyIgDj_-X9ihkQb-aLMRW82vlTyypaZsYf9025EzI4YTnHoOMoerMLkrcqvKTZ8ujcCMLr4gfR-b_Wbl4oV6DkegiWQwIA6QjFgMe403nSnzXPBPgVjpUYV2Jr_n3fi5tjEwr07sX5ij9j6w3OW1aJMTToTmJUdlkS2S4ny9V5LVQD-5P9vGFpNUMaOcJw7lXiG1eQV8fcfrkUmN2jSa5A3kAniVsvrZGQ-QbzsC8IvZGVfiVvqv_G7KoJDYqJUBYZJVRAwbdHOStNsEMcmmyb2f8xsvH23kqfTOYk7R5w"}'
      - PORT=4000
