ingress: "https://arbeidsplassen.intern.dev.nav.no"
loglevel: "debug"
namespace: "teampam"
pam_samtykke_api_url: "https://pam-samtykke-api-tokenx-proxy.dev-fss-pub.nais.io"
telemetry_url: "https://telemetry.ekstern.dev.nav.no/collect"