ingress: ["https://arbeidsplassen.dev.nav.no"]
loglevel: "debug"
ws_server_hostname: "arbeidsplassen.dev.nav.no"
namespace: "teampam"
loginurl: "https://arbeidsplassen.dev.nav.no/oauth2/login"
logouturl: "https://arbeidsplassen.dev.nav.no/oauth2/logout"
stillingssok: "https://arbeidsplassen.dev.nav.no/stillinger"
loginJobbsokerRedirectUrl: "https://arbeidsplassen.dev.nav.no/minside"
loginArbeidsgiverRedirectUrl: "https://arbeidsplassen.dev.nav.no/stillingsregistrering"
pam_samtykke_api_url: "https://pam-samtykke-api-tokenx-proxy.dev-fss-pub.nais.io"
