ingress: ["https://arbeidsplassen.dev.nav.no", "https://arbeidsplassen.intern.dev.nav.no"]
loglevel: "debug"
namespace: "teampam"
loginservice: "https://loginservice.dev.nav.no/login"
logoutservice: "https://loginservice.dev.nav.no/slo"
stillingssok: "https://arbeidsplassen.intern.dev.nav.no/stillinger"
loginJobbsokerRedirectUrl: "https://arbeidsplassen.intern.dev.nav.no/minside"
loginArbeidsgiverRedirectUrl: "https://arbeidsplassen.intern.dev.nav.no/stillingsregistrering"
pam_samtykke_api_url: "https://pam-samtykke-api-tokenx-proxy.dev-fss-pub.nais.io"
