ingress: ["https://arbeidsplassen.nav.no"]
loglevel: "error"
namespace: "teampam"
loginurl: "https://arbeidsplassen.nav.no/oauth2/login"
logouturl: "https://arbeidsplassen.nav.no/oauth2/logout"
stillingssok: "https://arbeidsplassen.nav.no/stillinger"
loginJobbsokerRedirectUrl: "https://arbeidsplassen.nav.no/minside"
loginArbeidsgiverRedirectUrl: "https://arbeidsplassen.nav.no/stillingsregistrering"
pam_samtykke_api_url: "https://pam-samtykke-api-tokenx-proxy.prod-fss-pub.nais.io"
