ingress: ["https://arbeidsplassen.nav.no"]
loglevel: "error"
namespace: "teampam"
pam_samtykke_api_url: "https://pam-samtykke-api-tokenx-proxy.prod-fss-pub.nais.io"
amplitude_key: "a7b3f00008ae250a08c3ebbc6bf718f9"