name: Cypress Tests using Cypress Docker Image

on: 
    push:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - ".env.local"
            - "docker-compose.yml"
            - "LICENCE"
            - "CODEOWNERS"
        branches:
            - 'master'
            - 'feature/**'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
        id-token: write
        security-events: write
        actions: read
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
            GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        with:
          build: npm run build
          start: npm start
          browser: chrome