name: Cypress Tests using Cypress Docker Image

on: 
    push:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - ".env.local"
            - "docker-compose.yml"
            - "LICENCE"
            - "CODEOWNERS"
        branches:
            - 'master'
            - 'feature/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: npm
            registry-url: "https://npm.pkg.github.com"

        - run: npm ci --no-audit --prefer-offline
          env:
            NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            install: false
            start: npm run dev