name: deploy-prod
on:
  release:
    types: [published]

jobs:
  deploy-prod:
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v7
    with:
      NAIS_RESOURCE: .nais/nais.yml
      NAIS_VARS: .nais/prod.yml
