name: deploy-dev
on:
    push:
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - ".env.local"
            - "docker-compose.yml"
            - "LICENCE"
            - "CODEOWNERS"
        branches:
            - '*'

jobs:
    build-and-deploy:
        permissions:
            contents: write
            id-token: write
            security-events: write
            actions: read
        if: "(github.ref_name == 'main') || contains(github.event.head_commit.message, 'deploy:dev') || startsWith(github.ref, 'feature/')"
        uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v5
        with:
            LANGUAGE: "node"
            NODE_VERSION: "18"
            BUILD_CACHE: "npm"
            NAIS_RESOURCE: .nais/nais.yml
            NAIS_VARS: .nais/dev.yml
            SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'main' }}
        secrets:
            NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}
            NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
