name: validate-pr
on:
    pull_request:
        branches:
            - 'master'

jobs:
    validate-pr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "npm"
            - run: ./build.sh
              env:
                  OPTIONAL_SECRET: ${{ secrets.READER_TOKEN }}
            - run: npm run build

    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: test --org=teampam --severity-threshold=high
